### ISSUE TITLE
ctrl+shift+p not work in Mac VSCode

### ISSUE THREAD

**Issue by cen5bin** [ryzngard/header-source-switch#3]

**Comment by ryzngard** [comment]
For Mac, I believe it's it's Cmd+shift+P. Documentation for VSCode is at [https://code.visualstudio.com/docs/getstarted/userinterface](https://code.visualstudio.com/docs/getstarted/userinterface). 

I'll leave this open to update the document though, since it can be misleading

**Comment by ryzngard** [comment]
I've update the documentation on the next release planned.
