### ISSUE TITLE
Smarter switching with file name clashes

### ISSUE THREAD

**Issue by JakeArkinstall** [ryzngard/header-source-switch#4]
I am working on a large project, and in some cases there are multiple files with the same filenames, but in different directories. As an example:

* A
  * include
    * something.h
  * src
    * something.cpp
* B
  * include
    * something.h
  * src
    * something.cpp

(I should note that, in this specific project, this file structure makes sense - I promise!)

Whether I'm in directory A or B, switching header/source always ends up in (for example) directory A. Switching again ends up in directory A again, so switching twice starting from directory B will not return to the same file.

I would like to see a smarter approach, perhaps a recursive approach starting from the current directory, the parent directory, sibling directories (and so on), so that the resulting switch file is the closest matching relative of the current file.

**Comment by ryzngard** [comment]
I'm currently working on this after I update the codebase to match the latest standards for vscode templates. Hopefully will have this done in the next week. My current plan is to always choose the closest file, so the behavior is always the same.

**Comment by ryzngard** [comment]
I just release version 1.1.0 with a more intelligent algorithm. Let me know what you think! Closing for now
