### ISSUE TITLE
Feature request: Show corresponding header/source in split view

### ISSUE THREAD

**Issue by morgankdavis** [ryzngard/header-source-switch#6]
This is a follow up from an email with Andrew.

Xcode has a great feature that allows a secondary "Assistant Editor" (a split editor) to automatically "follow" the main editor.  If a C/C++/Obj-C header file is displayed in the main editor (usually by selecting it in the source tree), the second editor will automatically load up the corresponding implementation file.  Similarly, if an implementation file is opened in the main editor, the second editor automatically shows its header.  It would be awesome to have this feature in VSC!

I made a short video showing how it works in Xcode: [https://drive.google.com/open?id=1EwrUtXWZexu6PXDzQQmy8rsdWRH-nnil](https://drive.google.com/open?id=1EwrUtXWZexu6PXDzQQmy8rsdWRH-nnil)

Xcode is pretty fancy with its menus, but really all one would need to enjoy this feature in VSC would be a way to toggle "Split editor shows counterpart"

Let me know if I can help!

**Comment by ryzngard** [comment]
I've started working on this. I'll let you know when I have something working, and will publish a release with the feature enabled but marked as beta.

**Comment by ryzngard** [comment]
The latest code in master has this feature. This actually seems pretty minimal, so I'll just release as not beta soon. If you have a chance try it out!

**Comment by ryzngard** [comment]
1.3.0 is published with this feature

**Comment by morgankdavis** [comment]
This is really awesome!  Thank you!
